### ISSUE TITLE
Can't connect the LazerCube with TouchDesigner

### ISSUE THREAD

**Issue by HarryNorm** [NairoDorian/LaserCubeTD#4]
Hi,
We are trying to connect LazerCube with TouchDesigner with a lan connection. We don't know why but we follow this tutorial but we are not able to make TouchDesigner recognize the LazerCube. Can you help us please ? :)

**Comment by NairoDorian** [comment]
Do you have Discord or something to chat in real time ? 
Sent me a PM Nairod#1258

**Comment by HarryNorm** [comment]
Yes I just send you an invite on Discord

Le mar. 14 févr. 2023, à 11 h 58, NairoDorian ***@***.***> a
écrit :

**Comment by hlgwnt** [comment]
Hi,
We have the same problem. Have you found a solution?
LaserCube is working, IP is correct ,... still no connection possible.  :(

**Comment by bomanden** [comment]
I would also like to know which versions of the lasercube this project is compatible with :
7.5W Ultra
2.5W Ultra
2.5W WiFi
1.2W WiFi
Anyone tried with the current lasecube version above ?

**Comment by NairoDorian** [comment]
> I would also like to know which versions of the lasercube this project is compatible with : 7.5W Ultra 2.5W Ultra 2.5W WiFi 1.2W WiFi Anyone tried with the current lasecube version above ?

All above
It's written in the read me ....
